version: '3'
services:
  mysqlservice:
    image: mysql:latest
    container_name: mysql-standalone
    ports:
      - 3396:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
  springapp:
    build: .
    restart: on-failure
    ports:
     - 8082:8082
    depends_on: 
     - mysqlservice
