version: '3'
services:
  mysqlservice:
    image: mysql:latest
    container_name: mysql-standalone
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33061:3306
  springapp:
    build: .
    ports:
     - 8082:8082
    depends_on: 
     - mysqlservice
